#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


JACKPOT_JAR=`readlink -f "$0"`
JACKPOT_JAR=`dirname "$JACKPOT_JAR"`/jackpot.jar
JAVA=java
if [ -n "$JAVA_HOME" -a -x "$JAVA_HOME/bin/java" ] ; then
    JAVA="$JAVA_HOME/bin/java"
fi
# "jackpot scan|rewrite|try|inspections|doctor|help ..." is the agent-oriented
# command line; anything else is the original flag-based interface.
MAIN=org.netbeans.modules.jackpot30.cmdline.Main
case "$1" in
    scan|rewrite|try|inspections|doctor|help) MAIN=org.netbeans.modules.jackpot30.cmdline.AgentMain ;;
esac
exec "$JAVA" -XX:+IgnoreUnrecognizedVMOptions \
     -Djava.awt.headless=true \
     --add-opens=java.base/java.net=ALL-UNNAMED \
     --add-opens=java.desktop/sun.awt=ALL-UNNAMED \
     --add-opens=java.desktop/javax.swing.text=ALL-UNNAMED \
     $JACKPOT_OPTS \
     -classpath `dirname "$JACKPOT_JAR"`/jackpot.jar $MAIN "$@"
